### ISSUE TITLE
报错NameError: name 'ClusterBackend' is not defined

### ISSUE THREAD

**Issue by llzzzzoo** [alibaba-damo-academy/ParaClipper#16]
执行了`python paraclipper/launch.py`后报错error
`If you want to use the speaker diarization, please `pip install hdbscan`
If you want use mossformer, lease install rotary_embedding_torch by: 
 pip install -U rotary_embedding_torch
If you want use mossformer, lease install rotary_embedding_torch by: 
 pip install -U rotary_embedding_torch
If you want use mossformer, lease install rotary_embedding_torch by: 
 pip install -U rotary_embedding_torch
If you want use mossformer, lease install rotary_embedding_torch by: 
 pip install -U rotary_embedding_torch
2024-03-02 22:31:26,478 - modelscope - INFO - PyTorch version 2.2.1 Found.
2024-03-02 22:31:26,483 - modelscope - INFO - TensorFlow version 2.13.1 Found.
2024-03-02 22:31:26,485 - modelscope - INFO - Loading ast index from /home/lzo/.cache/modelscope/ast_indexer
2024-03-02 22:31:26,909 - modelscope - INFO - Loading done! Current index file version is 1.12.0, with md5 a986dd5e37b563e607171cc5fb7e9553 and a total number of 964 components indexed
2024-03-02 22:31:27,715 - modelscope - INFO - Use user-specified model revision: v2.0.4
ckpt: /home/lzo/.cache/modelscope/hub/iic/speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch/model.pt
2024-03-02 22:31:41,582 - modelscope - INFO - Use user-specified model revision: v2.0.4
ckpt: /home/lzo/.cache/modelscope/hub/damo/speech_fsmn_vad_zh-cn-16k-common-pytorch/model.pt
2024-03-02 22:31:42,485 - modelscope - INFO - Use user-specified model revision: v2.0.4
ckpt: /home/lzo/.cache/modelscope/hub/damo/punc_ct-transformer_zh-cn-common-vocab272727-pytorch/model.pt
2024-03-02 22:31:44,738 - modelscope - INFO - Use user-specified model revision: v2.0.2
ckpt: /home/lzo/.cache/modelscope/hub/damo/speech_campplus_sv_zh-cn_16k-common/campplus_cn_common.bin
Traceback (most recent call last):
  File "paraclipper/launch.py", line 7, in <module>
    funasr_model = AutoModel(model="iic/speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch",
  File "/home/lzo/anaconda3/envs/ParaClipper/lib/python3.8/site-packages/funasr/auto/auto_model.py", line 126, in __init__
    self.cb_model = ClusterBackend().to(kwargs["device"])
NameError: name 'ClusterBackend' is not defined
`

**Comment by R1ckShi** [comment]
在你发的log第二行有哈，安装一下hdbscan

**Comment by llzzzzoo** [comment]
安装完hdbscan和rotary_embedding_torch输入`python paraclipper/launch.py`
又报错`When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to allow access to localhost`
不过在`launch.py`文件里面添加了
```
import os
os.environ["no_proxy"] = "localhost,127.0.0.1,::1"
```
后运行成功
